apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
 
namespace: dev
 
namePrefix: dev-
 
 
 
resources:
- ../../base
labels:
- includeSelectors: true
  pairs:
    environment: dev
patches:
- path: replica-patch.yaml
