apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/resources
spec:
  project: default
  source:
    repoURL: https://github.com/andalfaya/k8s-gitops-demo
    targetRevision: master
    path: overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
