apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

namePrefix: staging-



resources:
- ../../base
labels:
- includeSelectors: true
  pairs:
    environment: staging
patches:
- path: replica-patch.yaml
