apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

namePrefix: prod-



resources:
- ../../base
labels:
- includeSelectors: true
  pairs:
    environment: prod
patches:
- path: replica-patch.yaml
